language: node_js

node_js:
  - 0.8
  - 0.10

before_script:
  # install dependencis
  - gem update --system
  - gem install bundler
  - bundle install
  - npm install -g grunt-cli phantomjs testem

script:
  - testem ci > tests.tap 
